import { Terminal, Key, Lock, Type, User, Wallet, FileText, Globe, Hash, Phone, Mail, Calendar, Clock, Link } from 'lucide-react';

export const fieldTypes = [
  {
    value: 'text',
    label: 'Text',
    icon: Type,
    description: 'Simple text field',
    style: 'bg-gradient-to-br from-violet-500/5 via-fuchsia-500/5 to-cyan-500/5',
    iconStyle: 'from-violet-500 to-fuchsia-500',
    badge: 'Basic',
    badgeStyle: 'from-violet-500 to-fuchsia-500',
  },
  {
    value: 'code',
    label: 'Code Block',
    icon: Terminal,
    description: 'Terminal-style code editor',
    style: 'bg-gradient-to-br from-cyan-500/5 via-blue-500/5 to-indigo-500/5',
    iconStyle: 'from-cyan-500 to-blue-500',
    badge: 'Terminal',
    badgeStyle: 'from-cyan-500 to-blue-500',
  },
  {
    value: 'password',
    label: 'Password',
    icon: Lock,
    description: 'Secure password field',
    style: 'bg-gradient-to-br from-rose-500/5 via-pink-500/5 to-fuchsia-500/5',
    iconStyle: 'from-rose-500 to-pink-500',
    badge: 'Secure',
    badgeStyle: 'from-rose-500 to-pink-500',
  },
  {
    value: 'key',
    label: 'API Key',
    icon: Key,
    description: 'API key or token',
    style: 'bg-gradient-to-br from-amber-500/5 via-orange-500/5 to-red-500/5',
    iconStyle: 'from-amber-500 to-orange-500',
    badge: 'Secret',
    badgeStyle: 'from-amber-500 to-orange-500',
  },
  {
    value: 'url',
    label: 'URL',
    icon: Link,
    description: 'Website or API endpoint',
    style: 'bg-gradient-to-br from-emerald-500/5 via-teal-500/5 to-cyan-500/5',
    iconStyle: 'from-emerald-500 to-teal-500',
    badge: 'Link',
    badgeStyle: 'from-emerald-500 to-teal-500',
  },
  {
    value: 'email',
    label: 'Email',
    icon: Mail,
    description: 'Email address',
    style: 'bg-gradient-to-br from-blue-500/5 via-indigo-500/5 to-violet-500/5',
    iconStyle: 'from-blue-500 to-indigo-500',
    badge: 'Email',
    badgeStyle: 'from-blue-500 to-indigo-500',
  },
  {
    value: 'username',
    label: 'Username',
    icon: User,
    description: 'Username or handle',
    style: 'bg-gradient-to-br from-violet-500/5 via-purple-500/5 to-fuchsia-500/5',
    iconStyle: 'from-violet-500 to-purple-500',
    badge: 'User',
    badgeStyle: 'from-violet-500 to-purple-500',
  },
  {
    value: 'wallet',
    label: 'Wallet',
    icon: Wallet,
    description: 'Crypto wallet address',
    style: 'bg-gradient-to-br from-fuchsia-500/5 via-pink-500/5 to-rose-500/5',
    iconStyle: 'from-fuchsia-500 to-pink-500',
    badge: 'Crypto',
    badgeStyle: 'from-fuchsia-500 to-pink-500',
  },
  {
    value: 'note',
    label: 'Note',
    icon: FileText,
    description: 'Notepad-style text editor',
    style: 'bg-gradient-to-br from-teal-500/5 via-emerald-500/5 to-green-500/5',
    iconStyle: 'from-teal-500 to-emerald-500',
    badge: 'Note',
    badgeStyle: 'from-teal-500 to-emerald-500',
  },
  {
    value: 'number',
    label: 'Number',
    icon: Hash,
    description: 'Numeric value',
    style: 'bg-gradient-to-br from-cyan-500/5 via-sky-500/5 to-blue-500/5',
    iconStyle: 'from-cyan-500 to-sky-500',
    badge: 'Number',
    badgeStyle: 'from-cyan-500 to-sky-500',
  },
  {
    value: 'phone',
    label: 'Phone',
    icon: Phone,
    description: 'Phone number',
    style: 'bg-gradient-to-br from-indigo-500/5 via-violet-500/5 to-purple-500/5',
    iconStyle: 'from-indigo-500 to-violet-500',
    badge: 'Phone',
    badgeStyle: 'from-indigo-500 to-violet-500',
  },
  {
    value: 'date',
    label: 'Date',
    icon: Calendar,
    description: 'Date picker',
    style: 'bg-gradient-to-br from-orange-500/5 via-amber-500/5 to-yellow-500/5',
    iconStyle: 'from-orange-500 to-amber-500',
    badge: 'Date',
    badgeStyle: 'from-orange-500 to-amber-500',
  },
  {
    value: 'time',
    label: 'Time',
    icon: Clock,
    description: 'Time picker',
    style: 'bg-gradient-to-br from-rose-500/5 via-red-500/5 to-orange-500/5',
    iconStyle: 'from-rose-500 to-red-500',
    badge: 'Time',
    badgeStyle: 'from-rose-500 to-red-500',
  },
];
