import { Terminal, Key, Lock, Type, User, Wallet, FileText, Globe, Hash, Phone } from 'lucide-react';

export const fieldTypes = [
  {
    value: 'text',
    label: 'Text',
    icon: Type,
    description: 'Simple text field',
    style: 'bg-gradient-to-r from-zinc-500/5 to-zinc-500/5',
    iconStyle: 'bg-zinc-500/10 text-zinc-500',
  },
  {
    value: 'code',
    label: 'Code Block',
    icon: Terminal,
    description: 'Terminal-style code editor',
    style: 'bg-gradient-to-r from-emerald-500/5 to-cyan-500/5',
    iconStyle: 'bg-emerald-500/10 text-emerald-500',
    badge: 'Terminal',
    badgeStyle: 'bg-emerald-500/10 text-emerald-500',
  },
  {
    value: 'password',
    label: 'Password',
    icon: Lock,
    description: 'Secure password field',
    style: 'bg-gradient-to-r from-red-500/5 to-pink-500/5',
    iconStyle: 'bg-red-500/10 text-red-500',
    badge: 'Secure',
    badgeStyle: 'bg-red-500/10 text-red-500',
  },
  {
    value: 'key',
    label: 'API Key',
    icon: Key,
    description: 'API key or token',
    style: 'bg-gradient-to-r from-amber-500/5 to-yellow-500/5',
    iconStyle: 'bg-amber-500/10 text-amber-500',
    badge: 'Secret',
    badgeStyle: 'bg-amber-500/10 text-amber-500',
  },
  {
    value: 'url',
    label: 'URL',
    icon: Globe,
    description: 'Website or API endpoint',
    style: 'bg-gradient-to-r from-blue-500/5 to-indigo-500/5',
    iconStyle: 'bg-blue-500/10 text-blue-500',
  },
  {
    value: 'username',
    label: 'Username',
    icon: User,
    description: 'Username or email',
    style: 'bg-gradient-to-r from-purple-500/5 to-violet-500/5',
    iconStyle: 'bg-purple-500/10 text-purple-500',
  },
  {
    value: 'wallet',
    label: 'Wallet',
    icon: Wallet,
    description: 'Crypto wallet address',
    style: 'bg-gradient-to-r from-orange-500/5 to-red-500/5',
    iconStyle: 'bg-orange-500/10 text-orange-500',
  },
  {
    value: 'note',
    label: 'Note',
    icon: FileText,
    description: 'Notepad-style text editor',
    style: 'bg-gradient-to-r from-amber-500/5 to-yellow-500/5',
    iconStyle: 'bg-amber-500/10 text-amber-500',
    badge: 'Note',
    badgeStyle: 'bg-amber-500/10 text-amber-500',
  },
  {
    value: 'number',
    label: 'Number',
    icon: Hash,
    description: 'Numeric value',
    style: 'bg-gradient-to-br from-violet-500/10 via-purple-500/10 to-fuchsia-500/10',
    iconStyle: 'bg-violet-500/10 text-violet-500',
  },
  {
    value: 'phone',
    label: 'Phone',
    icon: Phone,
    description: 'Phone number',
    style: 'bg-gradient-to-r from-emerald-500/10 to-teal-500/10',
    iconStyle: 'bg-emerald-500/10 text-emerald-500',
  },
];
